### ISSUE TITLE
Broken after sdk 37 upgrade

### ISSUE THREAD

**Issue by dincozdemir** [expo/match-media#13]
Hello, 

`import '@expo/match-media';` doesnt seem to be working ufter an upgrade from sdk 36 to 37

![Screenshot from 2020-04-16 09-21-39](https://user-images.githubusercontent.com/2143920/79426716-d5c48d80-7fc3-11ea-8488-c79477526b8a.png)

**Comment by efleurine** [comment]
It seems that `ScreenOrientiation` is now in a separate package

`expo install expo-screen-orientation`

**Comment by EvanBacon** [comment]
Fixed in 0.0.0-beta.2
