### ISSUE TITLE
undefined is not an object: ScreenOrientation.default.Orientation

### ISSUE THREAD

**Issue by xiCO2k** [expo/match-media#7]
With Expo SDK 36:

undefined is not an object (evaluating '_ScreenOrientation.default.Orientation')
- node_modules/@expo/match-media/build/polyfill.native.js:7:8 in MediaQuery#constructor

file
![image](https://user-images.githubusercontent.com/823088/71278410-7032fe00-234f-11ea-9dc2-6cc5f504c7ef.png)

**Comment by venits** [comment]
This issue is fixed in the *"newest*" version.

To install the newest version run:
`yarn add @expo/match-media@alpha`

**Comment by xiCO2k** [comment]
Awesome Thanks

**Comment by RWOverdijk** [comment]
@venits It's still there on bare.

**Comment by xiCO2k** [comment]
@venits still gives the issue on ^0.0.0-alpha.5

**Comment by venits** [comment]
@xiCO2k  Yep the issue is back in Expo 37 ;/

They moved `ScreenOrientation` to separate module `expo-screen-orientation`

In this module you still can see:
`import { ScreenOrientation } from "expo";`

It is pretty easy to fix but probably won't happen soon :D

**Comment by xiCO2k** [comment]
@EvanBacon can you check this? Thanks

**Comment by NoemiRozpara** [comment]
This is still an issue - could this one be reopened and the mentioned PR checked? 🙏

**Comment by thegeekybaniya** [comment]
Still not fixed

**Comment by NoemiRozpara** [comment]
@thegeekybaniya @xiCO2k I have checked that locally using `yarn link` and it doesn't throw import error any more, but the app loads forever. I guess it might be some listener issue, but I don't have more time right now to help
